name: 02 - Workflow Events
on: 
    # schedule:
    #     - cron: '*/1 * * * *'
    push:
    pull_request:
    workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Event name
              run: |
               echo "Event name: ${{ github.event_name }}"