name: '07 - Using Expressions'
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}
on:
    push:
      branches:
        - main
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print start-up data'
              if: ${{ inputs.debug }}
              shell: bash
              run: |
                 echo "Triggered by: ${{ github.event_name }}"
                 echo "Branch: ${{ github.ref }}"
                 echo "SHA: ${{ github.sha }}"
                 echo "Runner os: ${{ runner.os }}"
            - name: '[debug] Print start-up data'
              if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
              shell: bash
              run: |
                 echo ""I was triggered from main""
            - name: 'Greeting'
              shell: bash
              run: echo "Hello World!"                 