name: '09-functions.yaml'
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: 'Failing step'
        run: exit 1
      - name: 'I will be skipped'
        run: echo "I will print if any previous step fails."
      