name: 15 - Working with matrices
on:
  workflow_dispatch:

jobs:
  backwards-compatability:
    name: ${{ matrix.os }}-${{ matrix.node-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
        os: 
          - windows-latest
          - ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with: ${{ matrix.node-version }}
      - name: Perform some tests
        run:  echo 'Running test for OS ${{ matrix.os}} and node-js version ${{ matrix.node-version}}'

    